### ISSUE TITLE
Survivaltest versions are not supported

### ISSUE THREAD

**Issue by DropTherapy** [MJZilogZ80/mcclw#1]
probably every other version outside of the list as well, but I tried c0.24_st_03 and it said it was running, but there wasn't a window besides the launcher.

**Comment by MJZilogZ80** [comment]
This is currently very close to being finished. In private testing using a more up to date version of the source code not yet currently on the GitHub, we've managed to get the following versions functional:
`	c0.30-3
	c0.30-2
	c0.30-1
	c0.30_01c
	c0.29_02
	c0.29_01
	c0.28_01
	c0.27_st
	c0.25_05_st
	c0.24_st_03
	in-20100201-2
	in-20100125-2
	in-20100111-1
	in-20100105`

**Comment by MJZilogZ80** [comment]
As of release 1.1, all survival test versions are supported. If you have any bugs surrounding those versions, feel free to start a new issue.
